=== Atlantidajas/JavaScript/leerXMLConJavaScript/xml/planetas.dtd
<!ELEMENT planetas (mercurio, venus, tierra, marte, jupiter, saturno, urano, nectuno, pluton)>
<!ELEMENT mercurio (nombre, diametro)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT diametro (#PCDATA)>
<!ELEMENT venus (#PCDATA)>
<!ELEMENT tierra (#PCDATA)>
<!ELEMENT marte (#PCDATA)>
<!ELEMENT jupiter (#PCDATA)>
<!ELEMENT saturno (#PCDATA)>
<!ELEMENT urano (#PCDATA)>
<!ELEMENT nectuno (#PCDATA)>
<!ELEMENT pluton (#PCDATA)>

=== Atlantidajas/JavaScript/leerXMLConJavaScript/xml/planetas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE planetas SYSTEM "file:///C:/Users/Jorge/Desktop/dtd/planetas.dtd">
<planetas>
    <mercurio>Mercurio</mercurio>
    <venus>Venus</venus>
    <tierra>Tierra</tierra>
    <marte>Marte</marte>
    <jupiter>Jupiter</jupiter>
    <saturno>Saturno</saturno>
    <urano>Urano</urano>
    <nectuno>Neptuno</nectuno>
    <pluton>Pluton</pluton>
  </planetas>
